### ISSUE TITLE
Don't generate anchor if there's no ID

### ISSUE THREAD

**Issue by allejo** [allejo/jekyll-anchor-headings#1]
If headings don't have an ID (creating manually with raw HTML), an anchor shouldn't be generated for them.

**Comment by garazdawi** [comment]
Hello!

In a project I recently switched from kramdown to commonmark to generate the HTML for markdown files, and one of the issues that I came across was that commonmark does not generate ids for its headers.

I've updated my local version of anchor_headings to create ids and add anchors for headers.

Would you like a PR for this where you can turn this functionality on with an option?

**Comment by allejo** [comment]
> I've updated my local version of anchor_headings to create ids and add anchors for headers.
> 
> Would you like a PR for this where you can turn this functionality on with an option?

Sure @garazdawi! I'd welcome that 😄 Especially since commonmark doesn't have this functionality built in and I know it's been complained about.
