### ISSUE TITLE
Aria, or other attribute support

### ISSUE THREAD

**Issue by WesCook** [allejo/jekyll-anchor-headings#12]
Hey,

Great plugin.  Very useful for a JS-free solution.

I was wondering if it was possible to add Aria support, or to pass along custom attributes?

I'm finding that screenreaders can take a lot longer to read out with an extra anchor after each header.  I think it'd be easier to mark them as `aria-hidden="true"`, or find another role to deemphasize them.

I'm not seeing how I'd pass this along without editing the script file itself though.  Would you consider making an attribute for aria, or accepting arbitrary attributes+values?

Thanks!

**Comment by WesCook** [comment]
Wonderful!  Thank you for the quick implementation.  :)

**Comment by allejo** [comment]
No problem!

I was considering adding an `aria-hidden` by default but decided against that to allow users to handle accessibility however they see fit. I alone was able to think of several different ways to handle it depending on the site so I didn't want to impose any one of them on users.
