### ISSUE TITLE
Headings inside header elements cause broken HTML with missing text to be rendered

### ISSUE THREAD

**Issue by pdmosses** [allejo/jekyll-anchor-headings#21]
**My Markdown**

```markdown
<header>
  <h1 id="goodbye-world">Goodbye World</h1>
  <p>some header text</p>
</header>
```

**Snippet Usage**

```liquid
{% capture markdown %}
<header>
  <h1 id="goodbye-world">Goodbye World</h1>
  <p>some header text</p>
</header>
{% endcapture %}
{% assign text = markdown | markdownify %}

<div>
{% include anchor_headings.html html=text %}
</div>
```

**Expected HTML**

```html
<div>
  <header>
    <h1 id="goodbye-world">Goodbye World <a href="#goodbye-world"></a></h1>
    <p>some header text</p>
  </header>
</div>
```

**Actual HTML**

```html
<div>
<header>
      <h1 id="goodbye-world">
        
        
          Goodbye World <a href="#goodbye-world"></a>
        
        
      </header>

</div>
```

**Notes**

Various Jekyll themes use this pattern of HTML for posts in blogs – even [Minima](https://github.com/jekyll/minima/blob/master/_layouts/post.html). The test for the fix for issue #13 doesn't include nested elements.

**Comment by pdmosses** [comment]
@allejo many thanks for fixing this so quickly!

**Comment by allejo** [comment]
Thanks for the clean bug report @pdmosses :smile:

Tagged [v1.0.7](https://github.com/allejo/jekyll-anchor-headings/releases/tag/v1.0.7) :tada:
