### ISSUE TITLE
">" should be added?

### ISSUE THREAD

**Issue by CrystalBallBe** [allejo/jekyll-anchor-headings#26]
I don't have any confidence, but it seems to me that `>` should be added to the end of [this line](https://github.com/allejo/jekyll-anchor-headings/blob/b53cbb341758d22fe52037ee686119b44d075a8a/_includes/anchor_headings.html#L129). When I open this source, my editor warns me that there is no `>`.

**Comment by allejo** [comment]
Under any other circumstance, you would have been right, a `>` is missing from that line. But if follow the value of `_hAttrToStrip` up a bit to these two spots, you'll see that this is where the `>` is being added.

https://github.com/allejo/jekyll-anchor-headings/blob/b53cbb341758d22fe52037ee686119b44d075a8a/_includes/anchor_headings.html#L93

https://github.com/allejo/jekyll-anchor-headings/blob/b53cbb341758d22fe52037ee686119b44d075a8a/_includes/anchor_headings.html#L101

If you ask _why_ it's needed up there, I wouldn't be able to give you an answer without remembering what sorcery I did here. But if you try moving the `>`, build the unit tests, and run the tests you'll see that it won't work.

**Comment by CrystalBallBe** [comment]
got it! thank you for the details.
