### ISSUE TITLE
Strip HTML in %heading% for anchorTitle

### ISSUE THREAD

**Issue by nonsensation** [allejo/jekyll-anchor-headings#27]
First of all, thank you very much for this project as well as jekyll-TOC, your work is excellent and just filling the gap that is missing in jekyll for GH-Pages.
 
---

When having an anchor in headings and using `%heading%` in `anchorTitle`, the generated HTML breaks.

**Markdown**

```markdown
### The [`match`](#match) Expression
```

**Snippet Usage**

```liquid
{% include anchor_headings.html
  beforeHeading=false
  h_min=2
  html=content
  anchorClass="permalink icon-link"
  anchorBody=""
  anchorTitle="Permalink for '%heading%'"
%}
```

**Expected HTML**

```html
<h3 id="the-match-expression">
    The <a href="#match"><code class="language-text highlighter-rouge">match</code></a> Expression
    <a href="#the-match-expression" class="permalink icon-link" title="Permalink for 'The match Expression'"></a>
</h3>
```

**Actual HTML**

```html
<h3 id="the-match-expression">
    The <a href="#match"><code class="language-text highlighter-rouge">match</code></a> Expression
    <a href="#the-match-expression" class="permalink icon-link"
        title="Permalink for 'The <a href="#match"><code class="language-text highlighter-rouge">match</code></a> Expression'">
    </a>
</h3>
```

**Notes**

To fix this, I added `| strip_html ` in line 111 for `if include.anchorTitle`:

```
{% if include.anchorTitle %}
  {% capture anchor %}{{ anchor }} title="{{ include.anchorTitle | replace: '%heading%', header | strip_html }}"{% endcapture %}
{% endif %}
```

---

I am not firm with liquid, I have had this issue only with `anchorTitle`, but maybe this will pop up elsewhere as well.

**Comment by allejo** [comment]
I'm glad both this and jekyll-toc were able to work for you :smile:

I've tagged v1.0.9 that fixes `%heading%` being stripped of HTML in all its locations
