### ISSUE TITLE
Accessibility issue: [aria-hidden="true"] elements contain focusable descendants

### ISSUE THREAD

**Issue by askel45** [allejo/jekyll-anchor-headings#30]
Hi. After the solution in issue #29, again a new accessibility issue https://web.dev/aria-hidden-focus/. I use the headings ID only for a few posts to create a Table of Contents. Is there a way to edit the code to retain the ID but remove the `<a></a>` link?

**Comment by allejo** [comment]
Hmm I don't quite follow? This snippet does not create IDs for the headings, it creates the `<a>` themselves for people to be able to permalink to those headings. But the IDs themselves are generated by your markdown engine.

As for an ARIA hidden focus, that'd make sense... I guess a `tabindex="-1"` would allow it to not be focusable.
