### ISSUE TITLE
Messes with horizontal rules

### ISSUE THREAD

**Issue by timakro** [allejo/jekyll-anchor-headings#9]
The `<hr>` tag (and possibly other HTML tags starting with "h") is butchered.

All that is left turns out the be a sad and lonely

```
r />
```

:(

**Comment by allejo** [comment]
Thanks for the find, @timakro! Fixed in [1.0.3](https://github.com/allejo/jekyll-anchor-headings/releases/tag/v1.0.3) :tada:
